version: "3"
services:
  kindlebot:
    image: nerdneils/kindlebot
    restart: always
    volumes:
      - "./config.toml:/usr/src/app/kindlebot.toml"
      - "./TEMP:/usr/src/app/TEMP"
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "./data:/data"
    command: ["redis-server", "--appendonly", "yes"]
